### ISSUE TITLE
Docs checklist

### ISSUE THREAD

**Issue by lionello** [defang-io/defang-docs#1]
- [x] remove landing page when clicking on logo
- [x] remove all example Docusaurus content (blog, tutorials etc.)
- [x] decide on per-language sub-pages (w/ buttons) vs tabs
